# Generated by Django 2.2 on 2019-10-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='depiction',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project',
            new_name='name',
        ),
    ]
